window:

  opacity: 0.75

font:
    size: 7
    normal:
      family: SourceCodePro
padding : 6.0,6.0,6.0,6.0

background": "#FFFFFF"
foreground": "#c7e0ea"
cursor": "#c7e0ea"

  #colors": {
  #       color0": "#0D1323",
  #       color1: "#698CA7",
  #       color2: "#62A2D3",
  #       color3: "#72C8E9",
  #       color4: "#92A1AC",
  #       color5: "#D7A8BA",
  #       color6: "#96B4CE",
  #       color7: "#c7e0ea",
  #       color8: "#8b9ca3",
  #       color9: "#698CA7",
  #       color10:"#62A2D3",
  #       color11:"#72C8E9",
  #       color12:"#92A1AC",
  #     }    

